
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env ##This is for dev enviroment only. Do not use in production
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: yarn start:dev
    networks:
      - backend

networks:
  backend:
    driver: bridge
