export enum ConfigKey {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_KEY = 'API_KEY',
  RATE_LIMIT_GLOBAL = 'RATE_LIMIT_GLOBAL',
  RATE_LIMIT_WINDOW_MS = 'RATE_LIMIT_WINDOW_MS',
  JWT_PUBLIC_KEY_DEV = 'JWT_PUBLIC_KEY_DEV',
  JWT_PUBLIC_KEY_PROD = 'JWT_PUBLIC_KEY_PROD',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  ENABLE_HTTPS = 'ENABLE_HTTPS',
  CORS_ORIGIN = 'CORS_ORIGIN',

  // Logging Configuration
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_TO_CONSOLE = 'LOG_TO_CONSOLE',
  LOG_TO_FILE = 'LOG_TO_FILE',
  LOG_FILE_PATH = 'LOG_FILE_PATH',

  AUTH_PROXY_SERVICE_BASE_URL = 'AUTH_PROXY_SERVICE_BASE_URL',
}
