name: Release Please

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: 'node'
          package-name: 'synkpay-api-gateway-v0'
          changelog-types: |
            [
              {"type": "feat", "section": "Features"},
              {"type": "fix", "section": "Bug Fixes"}
            ]
          bump-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}